version: '3'
volumes:
  db-amparo-volume:
services:
  amparo-db:
    image: "postgres:12.3"
    ports:
      - "5432:5432"
    volumes:
      - db-painelatualizacao-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=painel
      - POSTGRES_DB=painelatualizacao-db
      - POSTGRES_USER=painel